# Generated by Django 3.1.2 on 2020-10-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='description',
        ),
    ]
