# Generated by Django 3.1.2 on 2020-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attachment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('image', 'IMAGE')], max_length=15, null=True),
        ),
    ]
