# Generated by Django 3.1.2 on 2020-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201103_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
