# Generated by Django 3.1.2 on 2020-11-12 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_bonding',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeletal_class', models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200)),
                ('nasolabial_angle', models.CharField(choices=[('normal', 'NORMAL'), ('acute', 'ACUTE'), ('obtuse', 'OBTUCE')], default='class1', max_length=200)),
                ('nasolabial_sulcus', models.CharField(choices=[('normal', 'NORMAL'), ('deep', 'DEEP')], default='normal', max_length=200)),
                ('lip_competency', models.CharField(choices=[('competent', 'COMPETENT'), ('incompetent', 'INCOMPETENT'), ('partially_competent', 'PARTIALLY_COMPETENT')], default='competent', max_length=200)),
                ('face_form', models.CharField(choices=[('dolichocephalic', 'DOLICHOCEPHALIC'), ('mesocephalic', 'MESOCEPHALIC'), ('brachycephalic', 'BRACHYCEPHALIC')], default='dolichocephalic', max_length=200)),
                ('molar_class_left', models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200)),
                ('molar_class_right', models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='coincidence', max_length=200)),
                ('midline_upper', models.CharField(choices=[('coincidence', 'COINIDENCE'), ('deviated_to_left', 'DEVIATED TO LEFT'), ('deviated_to_right', 'DEVIATED TO RIGHT')], default='coincidence', max_length=200)),
                ('midline_lower', models.CharField(choices=[('coincidence', 'COINIDENCE'), ('deviated_to_left', 'DEVIATED TO LEFT'), ('deviated_to_right', 'DEVIATED TO RIGHT')], default='coincidence', max_length=200)),
                ('overjet', models.CharField(max_length=60)),
                ('Habit', models.CharField(max_length=60)),
                ('tongue_size', models.CharField(max_length=60)),
                ('oral_hygiene', models.CharField(choices=[('good', 'GOOD'), ('fair', 'FAIR'), ('bad', 'BAD')], default='good', max_length=200)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('treated_arch', models.CharField(choices=[('max', 'MAX'), ('mand', 'MAND')], default='max', max_length=200)),
                ('bracket_system', models.CharField(max_length=60)),
                ('slot', models.CharField(max_length=60)),
                ('extraction_upper', models.CharField(max_length=60)),
                ('extraction_lower', models.CharField(max_length=60)),
                ('anchorage_upper', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.patient')),
            ],
        ),
    ]
