# Generated by Django 3.1.2 on 2020-11-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexamination',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.patient'),
        ),
    ]
