# Generated by Django 3.1.2 on 2020-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201113_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexamination',
            name='Habit',
            field=models.CharField(default='Naughty', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='anchorage_upper',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='bracket_system',
            field=models.CharField(default='steel', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='extraction_lower',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='extraction_upper',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='overjet',
            field=models.CharField(default='Diskjet', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='slot',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='tongue_size',
            field=models.CharField(default='Long', max_length=60),
        ),
    ]
