# Generated by Django 3.1.2 on 2020-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201116_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexamination',
            name='molar_class_right',
            field=models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='nasolabial_angle',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('acute', 'ACUTE'), ('obtuse', 'OBTUCE')], default='normal', max_length=200),
        ),
    ]
