# Generated by Django 3.1.2 on 2020-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201116_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalexamination',
            old_name='Habit',
            new_name='habit',
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='anchorage_upper',
            field=models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='bracket_system',
            field=models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='extraction_lower',
            field=models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='extraction_upper',
            field=models.CharField(choices=[('class1', 'CLASS I'), ('class2', 'CLASS II'), ('class3', 'CLASS III')], default='class1', max_length=200),
        ),
    ]
