# Generated by Django 3.1.2 on 2020-11-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201118_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_restrictions', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('sinus_infections', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('diabetes', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('heart_problem', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('kidney_illness', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('emotional_difficulties', models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default=75, max_length=200)),
                ('other_diseasses', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicals', to='core.patient')),
            ],
        ),
    ]
