# Generated by Django 3.1.2 on 2020-11-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201118_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='emotional_difficulties',
            field=models.CharField(choices=[(95, 'EXCELENT'), (75, 'GOOD'), (50, 'FAIR'), (25, 'BAD'), (10, 'WORST')], default='GOOD', max_length=200),
        ),
    ]
