# Generated by Django 3.1.2 on 2020-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201118_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='diabetes',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='emotional_difficulties',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], default='75', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='heart_problem',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='kidney_illness',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='physical_restrictions',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='sinus_infections',
            field=models.CharField(choices=[('95', 'EXCELENT'), ('75', 'GOOD'), ('50', 'FAIR'), ('25', 'BAD'), ('10', 'WORST')], max_length=200),
        ),
    ]
