# Generated by Django 3.1.2 on 2020-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comingtreatment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingtreatment',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
